// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlowTziwFV-irGUAC5ifuRsWyR8ocFSUY',
    appId: '1:481147242979:android:3da702613a45bf6c6638d6',
    messagingSenderId: '481147242979',
    projectId: 'dnd-character-manager-81da9',
    storageBucket: 'dnd-character-manager-81da9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoV7DVZTRc9g8O4At7uqDyUwWCTIx-ikU',
    appId: '1:481147242979:ios:02b9f903ff31045e6638d6',
    messagingSenderId: '481147242979',
    projectId: 'dnd-character-manager-81da9',
    storageBucket: 'dnd-character-manager-81da9.firebasestorage.app',
    iosBundleId: 'com.JG.homeBrewed',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXS2d13dWzC0p1qZscyzm4kRWUPxP8flA',
    appId: '1:481147242979:web:e8b6b71264471ffb6638d6',
    messagingSenderId: '481147242979',
    projectId: 'dnd-character-manager-81da9',
    authDomain: 'dnd-character-manager-81da9.firebaseapp.com',
    storageBucket: 'dnd-character-manager-81da9.firebasestorage.app',
    measurementId: 'G-NGGDCKD53V',
  );

}