name: homeBrewed
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  flutter_bloc: ^9.0.0
  go_router: ^14.6.3
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.1
  email_validator: ^3.0.0
  equatable: ^2.0.5
  bloc: ^9.0.0
  google_fonts: ^6.1.0
  meta: ^1.11.0
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.7.0
  numberpicker: ^2.1.2
  uuid: ^4.3.3
  d20: ^0.3.1+1
  reactive_forms: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
