name: homeBrewed
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.4
  flutter_bloc: ^8.1.4
  go_router: ^13.2.0
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  email_validator: ^2.1.17
  equatable: ^2.0.5
  bloc: ^8.1.3
  google_fonts: ^6.1.0
  meta: ^1.11.0
  carousel_slider: ^4.2.1
  font_awesome_flutter: ^10.7.0
  numberpicker: ^2.1.2
  uuid: ^4.3.3
  d20: ^0.3.1+1
  reactive_forms: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
